"""Initial

Revision ID: f6e63078b43e
Revises: 
Create Date: 2026-02-24 22:15:10.119566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6e63078b43e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_slug'), 'banks', ['slug'], unique=True)
    op.create_table('deposit_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('open_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allow_topup', sa.Boolean(), nullable=False),
    sa.Column('allow_withdraw', sa.Boolean(), nullable=False),
    sa.Column('interest_payout', sa.String(length=20), nullable=False),
    sa.Column('capitalization', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('min_term_days', sa.Integer(), nullable=True),
    sa.Column('max_term_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_products_bank_id'), 'deposit_products', ['bank_id'], unique=False)
    op.create_index(op.f('ix_deposit_products_currency'), 'deposit_products', ['currency'], unique=False)
    op.create_table('deposit_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount_from', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_to', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('term_from_days', sa.Integer(), nullable=True),
    sa.Column('term_to_days', sa.Integer(), nullable=True),
    sa.Column('nominal_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['deposit_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_rates_product_id'), 'deposit_rates', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposit_rates_product_id'), table_name='deposit_rates')
    op.drop_table('deposit_rates')
    op.drop_index(op.f('ix_deposit_products_currency'), table_name='deposit_products')
    op.drop_index(op.f('ix_deposit_products_bank_id'), table_name='deposit_products')
    op.drop_table('deposit_products')
    op.drop_index(op.f('ix_banks_slug'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
